ALTER TABLE  hankittavat_paikalliset_tutkinnon_osat DROP COLUMN hoks_id;

ALTER TABLE  hankittavat_paikalliset_tutkinnon_osat ADD COLUMN hoks_id
INTEGER REFERENCES hoksit(id) ON DELETE CASCADE;

ALTER TABLE hankittavan_paikallisen_tutkinnon_osan_naytto DROP COLUMN
hankittava_paikallinen_tutkinnon_osa_id;

ALTER TABLE hankittavan_paikallisen_tutkinnon_osan_naytto
ADD COLUMN hankittava_paikallinen_tutkinnon_osa_id INTEGER
REFERENCES hankittavat_paikalliset_tutkinnon_osat(id) ON DELETE CASCADE;
