ALTER TABLE olemassa_olevan_ammatillisen_tutkinnon_osan_naytto RENAME TO
aiemmin_hankitun_ammat_tutkinnon_osan_naytto;

ALTER TABLE aiemmin_hankitun_ammat_tutkinnon_osan_naytto RENAME COLUMN
olemassa_oleva_ammatillinen_tutkinnon_osa_id TO
aiemmin_hankittu_ammat_tutkinnon_osa_id;

ALTER TABLE olemassa_olevat_ammatilliset_tutkinnon_osat RENAME TO
aiemmin_hankitut_ammat_tutkinnon_osat;

ALTER TABLE olemassa_olevan_paikallisen_tutkinnon_osan_arvioijat RENAME TO
aiemmin_hankitun_paikallisen_tutkinnon_osan_arvioijat;

ALTER TABLE aiemmin_hankitun_paikallisen_tutkinnon_osan_arvioijat RENAME COLUMN
olemassa_oleva_paikallinen_tutkinnon_osa_id TO
aiemmin_hankittu_paikallinen_tutkinnon_osa_id;

ALTER TABLE olemassa_olevan_paikallisen_tutkinnon_osan_naytto RENAME TO
aiemmin_hankitun_paikallisen_tutkinnon_osan_naytto;

ALTER TABLE aiemmin_hankitun_paikallisen_tutkinnon_osan_naytto RENAME COLUMN
olemassa_oleva_paikallinen_tutkinnon_osa_id TO
aiemmin_hankittu_paikallinen_tutkinnon_osa_id;

ALTER TABLE olemassa_olevan_yhteisen_tutkinnon_osan_arvioijat RENAME TO
aiemmin_hankitun_yhteisen_tutkinnon_osan_arvioijat;

ALTER TABLE aiemmin_hankitun_yhteisen_tutkinnon_osan_arvioijat RENAME COLUMN
olemassa_oleva_yhteinen_tutkinnon_osa_id TO
aiemmin_hankittu_yhteinen_tutkinnon_osa_id;

ALTER TABLE olemassa_olevan_yhteisen_tutkinnon_osan_naytto RENAME TO
aiemmin_hankitun_yhteisen_tutkinnon_osan_naytto;

ALTER TABLE aiemmin_hankitun_yhteisen_tutkinnon_osan_naytto RENAME COLUMN
olemassa_oleva_yhteinen_tutkinnon_osa_id TO
aiemmin_hankittu_yhteinen_tutkinnon_osa_id;

ALTER TABLE olemassa_olevan_yto_osa_alueen_naytto RENAME TO
aiemmin_hankitun_yto_osa_alueen_naytto;

ALTER TABLE aiemmin_hankitun_yto_osa_alueen_naytto RENAME COLUMN
olemassa_oleva_yto_osa_alue_id TO
aiemmin_hankittu_yto_osa_alue_id;

ALTER TABLE olemassa_olevat_paikalliset_tutkinnon_osat RENAME TO
aiemmin_hankitut_paikalliset_tutkinnon_osat;

ALTER TABLE olemassa_olevat_yhteiset_tutkinnon_osat RENAME TO
aiemmin_hankitut_yhteiset_tutkinnon_osat;

ALTER TABLE olemassa_olevat_yto_osa_alueet RENAME TO
aiemmin_hankitut_yto_osa_alueet;

ALTER TABLE aiemmin_hankitut_yto_osa_alueet RENAME COLUMN
olemassa_oleva_yhteinen_tutkinnon_osa_id TO
aiemmin_hankittu_yhteinen_tutkinnon_osa_id;
