ALTER TABLE  aiemmin_hankitut_paikalliset_tutkinnon_osat ADD COLUMN hoks_id_copy INTEGER REFERENCES hoksit(id) ON DELETE CASCADE;
UPDATE aiemmin_hankitut_paikalliset_tutkinnon_osat SET hoks_id_copy=hoks_id;
ALTER TABLE  aiemmin_hankitut_paikalliset_tutkinnon_osat DROP COLUMN hoks_id;
ALTER TABLE aiemmin_hankitut_paikalliset_tutkinnon_osat RENAME COLUMN hoks_id_copy TO hoks_id;

ALTER TABLE  aiemmin_hankitut_ammat_tutkinnon_osat ADD COLUMN hoks_id_copy INTEGER REFERENCES hoksit(id) ON DELETE CASCADE;
UPDATE aiemmin_hankitut_ammat_tutkinnon_osat SET hoks_id_copy=hoks_id;
ALTER TABLE  aiemmin_hankitut_ammat_tutkinnon_osat DROP COLUMN hoks_id;
ALTER TABLE aiemmin_hankitut_ammat_tutkinnon_osat RENAME COLUMN hoks_id_copy TO hoks_id;

ALTER TABLE  hankittavat_paikalliset_tutkinnon_osat ADD COLUMN hoks_id_copy INTEGER REFERENCES hoksit(id) ON DELETE CASCADE;
UPDATE hankittavat_paikalliset_tutkinnon_osat SET hoks_id_copy=hoks_id;
ALTER TABLE  hankittavat_paikalliset_tutkinnon_osat DROP COLUMN hoks_id;
ALTER TABLE hankittavat_paikalliset_tutkinnon_osat RENAME COLUMN hoks_id_copy TO hoks_id;

ALTER TABLE  aiemmin_hankitut_yhteiset_tutkinnon_osat ADD COLUMN hoks_id_copy INTEGER REFERENCES hoksit(id) ON DELETE CASCADE;
UPDATE aiemmin_hankitut_yhteiset_tutkinnon_osat SET hoks_id_copy=hoks_id;
ALTER TABLE  aiemmin_hankitut_yhteiset_tutkinnon_osat DROP COLUMN hoks_id;
ALTER TABLE aiemmin_hankitut_yhteiset_tutkinnon_osat RENAME COLUMN hoks_id_copy TO hoks_id;

ALTER TABLE  hankittavat_ammat_tutkinnon_osat ADD COLUMN hoks_id_copy INTEGER REFERENCES hoksit(id) ON DELETE CASCADE;
UPDATE hankittavat_ammat_tutkinnon_osat SET hoks_id_copy=hoks_id;
ALTER TABLE  hankittavat_ammat_tutkinnon_osat DROP COLUMN hoks_id;
ALTER TABLE hankittavat_ammat_tutkinnon_osat RENAME COLUMN hoks_id_copy TO hoks_id;

ALTER TABLE  opiskeluvalmiuksia_tukevat_opinnot ADD COLUMN hoks_id_copy INTEGER REFERENCES hoksit(id) ON DELETE CASCADE;
UPDATE opiskeluvalmiuksia_tukevat_opinnot SET hoks_id_copy=hoks_id;
ALTER TABLE  opiskeluvalmiuksia_tukevat_opinnot DROP COLUMN hoks_id;
ALTER TABLE opiskeluvalmiuksia_tukevat_opinnot RENAME COLUMN hoks_id_copy TO hoks_id;

ALTER TABLE  hankittavat_yhteiset_tutkinnon_osat ADD COLUMN hoks_id_copy INTEGER REFERENCES hoksit(id) ON DELETE CASCADE;
UPDATE hankittavat_yhteiset_tutkinnon_osat SET hoks_id_copy=hoks_id;
ALTER TABLE  hankittavat_yhteiset_tutkinnon_osat DROP COLUMN hoks_id;
ALTER TABLE hankittavat_yhteiset_tutkinnon_osat RENAME COLUMN hoks_id_copy TO hoks_id;

ALTER TABLE  hankittavan_paikallisen_tutkinnon_osan_naytto ADD COLUMN
hankittava_paikallinen_tutkinnon_osa_id_copy INTEGER REFERENCES hankittavat_paikalliset_tutkinnon_osat(id) ON DELETE CASCADE;
UPDATE hankittavan_paikallisen_tutkinnon_osan_naytto SET
hankittava_paikallinen_tutkinnon_osa_id_copy=hankittava_paikallinen_tutkinnon_osa_id;
ALTER TABLE  hankittavan_paikallisen_tutkinnon_osan_naytto
DROP COLUMN hankittava_paikallinen_tutkinnon_osa_id;
ALTER TABLE hankittavan_paikallisen_tutkinnon_osan_naytto RENAME COLUMN
hankittava_paikallinen_tutkinnon_osa_id_copy TO hankittava_paikallinen_tutkinnon_osa_id;

ALTER TABLE  hankittavan_paikallisen_tutkinnon_osan_osaamisen_hankkimistavat
ADD COLUMN hankittava_paikallinen_tutkinnon_osa_id_copy INTEGER REFERENCES
hankittavat_paikalliset_tutkinnon_osat(id) ON DELETE CASCADE;
UPDATE hankittavan_paikallisen_tutkinnon_osan_osaamisen_hankkimistavat
SET hankittava_paikallinen_tutkinnon_osa_id_copy=hankittava_paikallinen_tutkinnon_osa_id;
ALTER TABLE  hankittavan_paikallisen_tutkinnon_osan_osaamisen_hankkimistavat
DROP COLUMN hankittava_paikallinen_tutkinnon_osa_id;
ALTER TABLE hankittavan_paikallisen_tutkinnon_osan_osaamisen_hankkimistavat
RENAME COLUMN hankittava_paikallinen_tutkinnon_osa_id_copy TO hankittava_paikallinen_tutkinnon_osa_id;

ALTER TABLE  hankittavan_ammat_tutkinnon_osan_naytto ADD COLUMN
hankittava_ammat_tutkinnon_osa_id_copy INTEGER REFERENCES
hankittavat_ammat_tutkinnon_osat(id) ON DELETE CASCADE;
UPDATE hankittavan_ammat_tutkinnon_osan_naytto
SET hankittava_ammat_tutkinnon_osa_id_copy=hankittava_ammat_tutkinnon_osa_id;
ALTER TABLE  hankittavan_ammat_tutkinnon_osan_naytto DROP COLUMN hankittava_ammat_tutkinnon_osa_id;
ALTER TABLE hankittavan_ammat_tutkinnon_osan_naytto RENAME COLUMN
hankittava_ammat_tutkinnon_osa_id_copy TO hankittava_ammat_tutkinnon_osa_id;

ALTER TABLE  hankittavan_ammat_tutkinnon_osan_osaamisen_hankkimistavat
ADD COLUMN hankittava_ammat_tutkinnon_osa_id_copy INTEGER REFERENCES
hankittavat_ammat_tutkinnon_osat(id) ON DELETE CASCADE;
UPDATE hankittavan_ammat_tutkinnon_osan_osaamisen_hankkimistavat
SET hankittava_ammat_tutkinnon_osa_id_copy=hankittava_ammat_tutkinnon_osa_id;
ALTER TABLE  hankittavan_ammat_tutkinnon_osan_osaamisen_hankkimistavat
DROP COLUMN hankittava_ammat_tutkinnon_osa_id;
ALTER TABLE hankittavan_ammat_tutkinnon_osan_osaamisen_hankkimistavat
RENAME COLUMN hankittava_ammat_tutkinnon_osa_id_copy TO hankittava_ammat_tutkinnon_osa_id;

ALTER TABLE  yhteisen_tutkinnon_osan_osa_alueet ADD COLUMN
yhteinen_tutkinnon_osa_id_copy INTEGER REFERENCES
hankittavat_yhteiset_tutkinnon_osat(id) ON DELETE CASCADE;
UPDATE yhteisen_tutkinnon_osan_osa_alueet
SET yhteinen_tutkinnon_osa_id_copy=yhteinen_tutkinnon_osa_id;
ALTER TABLE  yhteisen_tutkinnon_osan_osa_alueet
DROP COLUMN yhteinen_tutkinnon_osa_id;
ALTER TABLE yhteisen_tutkinnon_osan_osa_alueet RENAME COLUMN
yhteinen_tutkinnon_osa_id_copy TO yhteinen_tutkinnon_osa_id;

ALTER TABLE  yhteisen_tutkinnon_osan_osa_alueen_osaamisen_hankkimistavat
ADD COLUMN yhteisen_tutkinnon_osan_osa_alue_id_copy INTEGER REFERENCES
yhteisen_tutkinnon_osan_osa_alueet(id) ON DELETE CASCADE;
UPDATE yhteisen_tutkinnon_osan_osa_alueen_osaamisen_hankkimistavat
SET yhteisen_tutkinnon_osan_osa_alue_id_copy=yhteisen_tutkinnon_osan_osa_alue_id;
ALTER TABLE  yhteisen_tutkinnon_osan_osa_alueen_osaamisen_hankkimistavat
DROP COLUMN yhteisen_tutkinnon_osan_osa_alue_id;
ALTER TABLE yhteisen_tutkinnon_osan_osa_alueen_osaamisen_hankkimistavat
RENAME COLUMN yhteisen_tutkinnon_osan_osa_alue_id_copy TO yhteisen_tutkinnon_osan_osa_alue_id;

ALTER TABLE  yhteisen_tutkinnon_osan_osa_alueen_naytot ADD COLUMN
yhteisen_tutkinnon_osan_osa_alue_id_copy INTEGER REFERENCES
yhteisen_tutkinnon_osan_osa_alueet(id) ON DELETE CASCADE;
UPDATE yhteisen_tutkinnon_osan_osa_alueen_naytot
SET yhteisen_tutkinnon_osan_osa_alue_id_copy=yhteisen_tutkinnon_osan_osa_alue_id;
ALTER TABLE  yhteisen_tutkinnon_osan_osa_alueen_naytot
DROP COLUMN yhteisen_tutkinnon_osan_osa_alue_id;
ALTER TABLE yhteisen_tutkinnon_osan_osa_alueen_naytot RENAME COLUMN
yhteisen_tutkinnon_osan_osa_alue_id_copy TO yhteisen_tutkinnon_osan_osa_alue_id;

ALTER TABLE  aiemmin_hankitun_ammat_tutkinnon_osan_naytto
ADD COLUMN aiemmin_hankittu_ammat_tutkinnon_osa_id_copy INTEGER REFERENCES
aiemmin_hankitut_ammat_tutkinnon_osat(id) ON DELETE CASCADE;
UPDATE aiemmin_hankitun_ammat_tutkinnon_osan_naytto
SET aiemmin_hankittu_ammat_tutkinnon_osa_id_copy=aiemmin_hankittu_ammat_tutkinnon_osa_id;
ALTER TABLE  aiemmin_hankitun_ammat_tutkinnon_osan_naytto
DROP COLUMN aiemmin_hankittu_ammat_tutkinnon_osa_id;
ALTER TABLE aiemmin_hankitun_ammat_tutkinnon_osan_naytto RENAME COLUMN
aiemmin_hankittu_ammat_tutkinnon_osa_id_copy TO aiemmin_hankittu_ammat_tutkinnon_osa_id;

ALTER TABLE  aiemmin_hankitun_paikallisen_tutkinnon_osan_naytto ADD COLUMN
aiemmin_hankittu_paikallinen_tutkinnon_osa_id_copy INTEGER REFERENCES
aiemmin_hankitut_paikalliset_tutkinnon_osat(id) ON DELETE CASCADE;
UPDATE aiemmin_hankitun_paikallisen_tutkinnon_osan_naytto SET
aiemmin_hankittu_paikallinen_tutkinnon_osa_id_copy=aiemmin_hankittu_paikallinen_tutkinnon_osa_id;
ALTER TABLE  aiemmin_hankitun_paikallisen_tutkinnon_osan_naytto
DROP COLUMN aiemmin_hankittu_paikallinen_tutkinnon_osa_id;
ALTER TABLE aiemmin_hankitun_paikallisen_tutkinnon_osan_naytto
RENAME COLUMN aiemmin_hankittu_paikallinen_tutkinnon_osa_id_copy TO aiemmin_hankittu_paikallinen_tutkinnon_osa_id;

ALTER TABLE  aiemmin_hankitun_paikallisen_tutkinnon_osan_arvioijat
ADD COLUMN aiemmin_hankittu_paikallinen_tutkinnon_osa_id_copy INTEGER REFERENCES
aiemmin_hankitut_paikalliset_tutkinnon_osat(id) ON DELETE CASCADE;
UPDATE aiemmin_hankitun_paikallisen_tutkinnon_osan_arvioijat
SET aiemmin_hankittu_paikallinen_tutkinnon_osa_id_copy=aiemmin_hankittu_paikallinen_tutkinnon_osa_id;
ALTER TABLE  aiemmin_hankitun_paikallisen_tutkinnon_osan_arvioijat
DROP COLUMN aiemmin_hankittu_paikallinen_tutkinnon_osa_id;
ALTER TABLE aiemmin_hankitun_paikallisen_tutkinnon_osan_arvioijat RENAME COLUMN
aiemmin_hankittu_paikallinen_tutkinnon_osa_id_copy TO aiemmin_hankittu_paikallinen_tutkinnon_osa_id;

ALTER TABLE  aiemmin_hankitun_yhteisen_tutkinnon_osan_naytto
ADD COLUMN aiemmin_hankittu_yhteinen_tutkinnon_osa_id_copy INTEGER REFERENCES
aiemmin_hankitut_yhteiset_tutkinnon_osat(id) ON DELETE CASCADE;
UPDATE aiemmin_hankitun_yhteisen_tutkinnon_osan_naytto
SET aiemmin_hankittu_yhteinen_tutkinnon_osa_id_copy=aiemmin_hankittu_yhteinen_tutkinnon_osa_id;
ALTER TABLE  aiemmin_hankitun_yhteisen_tutkinnon_osan_naytto
DROP COLUMN aiemmin_hankittu_yhteinen_tutkinnon_osa_id;
ALTER TABLE aiemmin_hankitun_yhteisen_tutkinnon_osan_naytto
RENAME COLUMN aiemmin_hankittu_yhteinen_tutkinnon_osa_id_copy TO aiemmin_hankittu_yhteinen_tutkinnon_osa_id;

ALTER TABLE  aiemmin_hankitun_yhteisen_tutkinnon_osan_arvioijat
ADD COLUMN aiemmin_hankittu_yhteinen_tutkinnon_osa_id_copy INTEGER REFERENCES
 aiemmin_hankitut_yhteiset_tutkinnon_osat(id) ON DELETE CASCADE;
UPDATE aiemmin_hankitun_yhteisen_tutkinnon_osan_arvioijat SET
aiemmin_hankittu_yhteinen_tutkinnon_osa_id_copy=aiemmin_hankittu_yhteinen_tutkinnon_osa_id;
ALTER TABLE  aiemmin_hankitun_yhteisen_tutkinnon_osan_arvioijat
DROP COLUMN aiemmin_hankittu_yhteinen_tutkinnon_osa_id;
ALTER TABLE aiemmin_hankitun_yhteisen_tutkinnon_osan_arvioijat
RENAME COLUMN aiemmin_hankittu_yhteinen_tutkinnon_osa_id_copy TO aiemmin_hankittu_yhteinen_tutkinnon_osa_id;

ALTER TABLE  aiemmin_hankitun_yto_osa_alueen_naytto ADD COLUMN
aiemmin_hankittu_yto_osa_alue_id_copy INTEGER REFERENCES
aiemmin_hankitut_yto_osa_alueet(id) ON DELETE CASCADE;
UPDATE aiemmin_hankitun_yto_osa_alueen_naytto SET
aiemmin_hankittu_yto_osa_alue_id_copy=aiemmin_hankittu_yto_osa_alue_id;
ALTER TABLE  aiemmin_hankitun_yto_osa_alueen_naytto
DROP COLUMN aiemmin_hankittu_yto_osa_alue_id;
ALTER TABLE aiemmin_hankitun_yto_osa_alueen_naytto RENAME COLUMN
aiemmin_hankittu_yto_osa_alue_id_copy TO aiemmin_hankittu_yto_osa_alue_id;

ALTER TABLE  aiemmin_hankitut_yto_osa_alueet ADD COLUMN
aiemmin_hankittu_yhteinen_tutkinnon_osa_id_copy INTEGER REFERENCES
aiemmin_hankitut_yhteiset_tutkinnon_osat(id) ON DELETE CASCADE;
UPDATE aiemmin_hankitut_yto_osa_alueet SET
aiemmin_hankittu_yhteinen_tutkinnon_osa_id_copy=aiemmin_hankittu_yhteinen_tutkinnon_osa_id;
ALTER TABLE  aiemmin_hankitut_yto_osa_alueet DROP COLUMN
aiemmin_hankittu_yhteinen_tutkinnon_osa_id;
ALTER TABLE aiemmin_hankitut_yto_osa_alueet RENAME COLUMN
aiemmin_hankittu_yhteinen_tutkinnon_osa_id_copy TO aiemmin_hankittu_yhteinen_tutkinnon_osa_id;
