ALTER TABLE puuttuvan_ammatillisen_tutkinnon_osan_naytto RENAME TO
hankittavan_ammatillisen_tutkinnon_osan_naytto;

ALTER TABLE hankittavan_ammatillisen_tutkinnon_osan_naytto RENAME COLUMN
puuttuva_ammatillinen_tutkinnon_osa_id TO
hankittava_ammatillinen_tutkinnon_osa_id;

ALTER TABLE puuttuvan_ammatillisen_tutkinnon_osan_osaamisen_hankkimistavat
RENAME TO hankittavan_ammat_tutkinnon_osan_osaamisen_hankkimistavat;

ALTER TABLE hankittavan_ammat_tutkinnon_osan_osaamisen_hankkimistavat
RENAME COLUMN puuttuva_ammatillinen_tutkinnon_osa_id TO
hankittava_ammatillinen_tutkinnon_osa_id;

ALTER TABLE puuttuvan_paikallisen_tutkinnon_osan_naytto RENAME TO
hankittavan_paikallisen_tutkinnon_osan_naytto;

ALTER TABLE hankittavan_paikallisen_tutkinnon_osan_naytto RENAME COLUMN
puuttuva_paikallinen_tutkinnon_osa_id TO
hankittava_paikallinen_tutkinnon_osa_id;

ALTER TABLE puuttuvan_paikallisen_tutkinnon_osan_osaamisen_hankkimistavat
RENAME TO hankittavan_paikallisen_tutkinnon_osan_osaamisen_hankkimistavat;

ALTER TABLE hankittavan_paikallisen_tutkinnon_osan_osaamisen_hankkimistavat
RENAME COLUMN puuttuva_paikallinen_tutkinnon_osa_id TO
hankittava_paikallinen_tutkinnon_osa_id;

ALTER TABLE puuttuvat_ammatilliset_tutkinnon_osat RENAME TO
hankittavat_ammatilliset_tutkinnon_osat;

ALTER TABLE puuttuvat_paikalliset_tutkinnon_osat RENAME TO
hankittavat_paikalliset_tutkinnon_osat;

ALTER TABLE puuttuvat_yhteiset_tutkinnon_osat RENAME TO
hankittavat_yhteiset_tutkinnon_osat;
