name: Create Lampi export runner image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Clone CI tools
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build the Docker image
        run: |
          source ci-tools/common/setup-tools.sh
          docker buildx build . --file scripts/lampi-export/Dockerfile --tag ${ECR_REPO}/ehoks-lampi-export:ga-${GITHUB_RUN_NUMBER} --platform linux/amd64

      - name: Upload Package
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          source ci-tools/common/setup-tools.sh
          ./ci-tools/github-build/upload-image.sh ehoks-lampi-export
